### PR TITLE
feat: add relation page

### LINKED ISSUE #97: Add Investor Relations Page
### Suggestion

Add Investor Relations Page to the Website.
You can take reference from here: https://www.zomato.com/investor-relations

image

image

image

### Use Cases

_No response_

### Related Problems

_No response_

### PR DESCRIPTION
**Pull request by hemant-sw**
I have successfully added the Relation page.
Closes #97 
cc - @Jai-Solania-29

### CODE REVIEW

**Review by SuperAayush — CHANGES_REQUESTED** [review]
Make the carousel moving or provide a button to switch between photos.
Also, try to make the page responsive or create a separate issue and start working for responsiveness.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Readable, Secure, Efficient

**Comment by hemant-sw** [comment]
Okay @SuperAayush  I will fix all mentioned  issues  as soon as possible .
Thanks.

**Comment by Jai-Solania-29** [comment]
Hey, @hemant-sw Can you please provide the screenshot of the work that you have done?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by hemant-sw** [comment]
investor2
investor3
invstor3
investor1

@Jai-Solania-29  please check attached  all screenshots & I deployed  this page on my repo.

**Review by Jai-Solania-29 — CHANGES_REQUESTED** [review]
Hey, @hemant-sw Please decrease the height of the Carousel, you can take reference from the official page of the Zomato website.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by hemant-sw** [comment]
Hey @Jai-Solania-29  as you mention I  fixed height of the Carousel please check before and after image.
investor1
carosuel


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Jai-Solania-29** [comment]
LGTM 🚀
Hey, @SuperAayush I would like to know your views before merging it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Review by SuperAayush — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
